//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunTakip_EntityFr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satıs
    {
        public int satısId { get; set; }
        public Nullable<int> s_urunId { get; set; }
        public Nullable<int> s_musteriId { get; set; }
        public Nullable<decimal> satısFiyat { get; set; }
        public Nullable<System.DateTime> satısTarih { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
